import type { ExpenseTemplate } from "./schemas";

export const SAVED_TEMPLATES: ExpenseTemplate[] = [
	{
		id: "swiggy-lunch",
		label: "Swiggy Lunch",
		pinned: true,
		name: "Swiggy Lunch",
		amount: 350,
		category: ["food"],
		payee: "Swiggy",
		paymentMode: "HDFC",
	},
	{
		id: "uber-office",
		label: "Uber Cab",
		pinned: true,
		name: "Uber Cab",
		amount: 250,
		category: ["transport"],
		payee: "Uber",
		paymentMode: "HDFC",
	},
	{
		id: "act-internet",
		label: "ACT Internet",
		pinned: true,
		name: "Internet Bill",
		amount: 1050,
		category: ["utilities"],
		payee: "ACT Fibernet",
		paymentMode: "HDFC",
	},
	{
		id: "rent",
		label: "Rent",
		name: "Monthly Rent",
		amount: 20000,
		category: ["rent"],
		payee: "Landlord",
		paymentMode: "HDFC",
	},
	{
		id: "starbucks",
		label: "Starbucks Coffee",
		name: "Starbucks Coffee",
		amount: 320,
		category: ["food"],
		payee: "Starbucks",
		paymentMode: "HDFC",
	},
	{
		id: "groceries",
		label: "Amazon Fresh",
		name: "Groceries",
		amount: 1500,
		category: ["groceries"],
		payee: "Amazon",
		paymentMode: "HDFC",
	},
	{
		id: "netflix",
		label: "Netflix Subscription",
		name: "Netflix",
		amount: 649,
		category: ["entertainment"],
		payee: "Netflix",
		paymentMode: "HDFC",
	},
	{
		id: "spotify",
		label: "Spotify",
		name: "Spotify",
		amount: 119,
		category: ["entertainment"],
		payee: "Spotify",
		paymentMode: "HDFC",
	},
	{
		id: "petrol",
		label: "Shell Petrol",
		name: "Petrol",
		amount: 1000,
		category: ["fuel"],
		payee: "Shell",
		paymentMode: "HDFC",
	},
];
